// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ECommerceContext))]
    partial class ECommerceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Entities.Concretes.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Apple's flagship iPhone with A17 Pro chip, titanium design, and 48MP camera",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "iPhone 15 Pro Max",
                            Price = 1199.99m,
                            Status = true,
                            Stock = 75
                        },
                        new
                        {
                            Id = 2,
                            Description = "Premium iPhone with A17 Pro chip, Action button, and titanium design",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "iPhone 15 Pro",
                            Price = 999.99m,
                            Status = true,
                            Stock = 85
                        },
                        new
                        {
                            Id = 3,
                            Description = "Latest standard iPhone with A16 Bionic chip and Dynamic Island",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "iPhone 15",
                            Price = 799.99m,
                            Status = true,
                            Stock = 90
                        },
                        new
                        {
                            Id = 4,
                            Description = "Previous generation premium iPhone with A16 Bionic chip and Dynamic Island",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "iPhone 14 Pro",
                            Price = 899.99m,
                            Status = true,
                            Stock = 65
                        },
                        new
                        {
                            Id = 5,
                            Description = "Compact iPhone with A15 Bionic chip and Touch ID",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "iPhone SE (2022)",
                            Price = 429.99m,
                            Status = true,
                            Stock = 100
                        },
                        new
                        {
                            Id = 6,
                            Description = "Samsung's flagship with Snapdragon 8 Gen 3, S Pen, and AI features",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 1299.99m,
                            Status = true,
                            Stock = 55
                        },
                        new
                        {
                            Id = 7,
                            Description = "Large display Galaxy with Snapdragon 8 Gen 3 and advanced camera system",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Samsung Galaxy S24+",
                            Price = 999.99m,
                            Status = true,
                            Stock = 60
                        },
                        new
                        {
                            Id = 8,
                            Description = "Standard Galaxy S series with powerful performance and AI features",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Samsung Galaxy S24",
                            Price = 799.99m,
                            Status = true,
                            Stock = 70
                        },
                        new
                        {
                            Id = 9,
                            Description = "Previous generation Ultra with Snapdragon 8 Gen 2 and 200MP camera",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Samsung Galaxy S23 Ultra",
                            Price = 1099.99m,
                            Status = true,
                            Stock = 50
                        },
                        new
                        {
                            Id = 10,
                            Description = "Previous generation S series with excellent camera and performance",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Samsung Galaxy S23",
                            Price = 699.99m,
                            Status = true,
                            Stock = 65
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
